config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  get "/products/search", to: "products#search"
  get "/products/:id/location", to: "products#location"
  get "/products/:id/sold", to: "products#sold", as: "sold"
  post "/products/:id/sold", to: "products#resale", as: "resale"
  resources :products, only: [:index, :show, :new, :create, :destroy] do
    collection do
      post "/checkout/:id", to: "products#checkout", as: "checkout"
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :categories, only: [:show]
  resources :users, only: [:show, :create]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new", as: "new_login"
  post "/login", to: "sessions#create", as: "create_login"
  delete "/logout", to: "sessions#destroy", as: "logout"
  get "/guest", to: "sessions#guest"
  resources :homes, only: [:index]
  resources :rooms, only: [:show, :create]
  resources :messages, only: [:create]
  resources :maps, only: [:index]
  get "/maps/search", to: "maps#search"
  resources :cards, only: [:show, :new] do
    collection do
      post "pay", to: "cards#pay"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :product
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  acts_as_mappable(default_units: :kms,
                   default_formula: :sphere,
                   distance_field_name: :distance,
                   lat_column_name: :latitude,
                   lng_column_name: :longitude)
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
  validates :user_id, presence: true
  validates :room_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_taxons, dependent: :destroy
  has_many :taxons, through: :product_taxons
  belongs_to :user
  has_one :room, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  has_one :map, dependent: :destroy
  accepts_nested_attributes_for :map

  validates :name, presence: true, length: { minimum: 2 }
  validates :description, presence: true
  validates :pickup_times, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :image, presence: true
  validate :image_size

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "5MB以下のファイルを添付して下さい")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).present?
  end
end

app/models/product_taxon.rb
class ProductTaxon < ApplicationRecord
  belongs_to :product
  belongs_to :taxon
  validates :taxon_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :memberships, dependent: :destroy
  belongs_to :product

  validates :product_id, presence: true
end

app/models/taxon.rb
class Taxon < ApplicationRecord
  has_many :product_taxons, dependent: :destroy
  has_many :products, through: :product_taxons
  acts_as_nested_set
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :memberships, dependent: :destroy

  authenticates_with_sorcery!
  mount_uploader :image, ImageUploader

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true,
                                    if: -> { new_record? || changes[:crypted_password] }
  validates_confirmation_of :password
  validate :image_size

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "5MB以下のファイルを添付して下さい")
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  skip_before_action :require_login
  def index
  end

  def search
    @latitude = params[:latitude]
    @longitude = params[:longitude]
    @maps = Map.includes(:product).within(3, origin: [params[:latitude], params[:longitude]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "prototype"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <script type="text/javascript" src="https://js.pay.jp/"></script>
    <script type="text/javascript">Payjp.setPublicKey("<%= ENV["PAYJP_PUBRIC_KEY"] %>");</script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Bitter:400,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "shared/header" %>
    </header>
    <%= yield %>
    <%= javascript_pack_tag 'hello_vue' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script> $('.dropdown-toggle').dropdown() </script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div class="error-explanation">
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: white;" >
  <div class="icon-header ">
    <%= link_to root_path, style: "color: #00b7ce;" do %>
      <%= icon "fab", "fort-awesome" %>
    <% end %>
  </div>

  <div class="collapse navbar-collapse" id="navbarNav01">
    <ul class="navbar-nav">
      <% if current_user %>
      <li class="nav-item">
        <div class="header-search-box">
          <form class="form-inline" action="/products/search" method="get" accept-charset="UTF-8" %>
            <input type="text" name="search" class="form-control mr-sm-2 search-input" placeholder="Search..">
            <button class="search-button">
              <span onclick="this.form.submit()">検索</span>
            </button>
          </form>
        </div>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav01" aria-controls="navbarNav01" aria-expanded="false" aria-label="ナビゲーション切り替え">
          <span class="navbar-toggler-icon"></span>
        </button>
      </li>
      <li class="nav-item">
        <div class="push-product-link">
          <%= link_to "出品する", new_product_path, method: :get, style: "color: #666666", class: "nav-link" %>
        </div>
      </li>
      <li class="nav-item active">
        <%= link_to "周辺のマップへ", maps_path, method: :get, style: "color: #666666;", class: "nav-link map-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "商品一覧", products_path, method: :get, style: "color: #666666;", class: "nav-link product-index-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", logout_path, method: :delete, style: "color: #666666;", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ユーザー管理", user_path(current_user.id), style: "color: #666666;", class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item active">
        <div class="header-emegency-button ">
          <%= link_to "簡易ログイン", guest_path, style: "color: #00b7ce" %>
        </div>
      </li>
      <li class="nav-item">
        <div class="else-map-link">
          <%= link_to "周辺のマップへ", maps_path, method: :get, style: "color: #666666;", class: "nav-link" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "商品一覧", products_path, method: :get, style: "color: #666666;", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ログイン" , new_login_path, method: :get, style: "color: #666666", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "ユーザー登録", signup_path, method: :get, style: "color: #666666", class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_product_segment.html.erb
<div class="col-md-3 product-space">
  <%= link_to product_path(product.id) do %>
    <div class="image-space">
      <% if product.state == "sold" %>
      <div class="sold-index-imageBox">
        <%= image_tag product.image.url(:product) %>
        <p>---SOLD OUT---</p>
      </div>
      <% else %>
       <%= image_tag product.image.url(:product) %>
      <% end %>
    </div>
    <div class="product-name-price-space">
      <div class="product-name-space"><%= product.name %></div>
      <div class="product-price-space">¥<%= product.price %></div>
    </div>
  <% end %>
</div>