config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  get "/products/search", to: "products#search"
  get "/products/:id/location", to: "products#location"
  get "/products/:id/sold", to: "products#sold", as: "sold"
  post "/products/:id/sold", to: "products#resale", as: "resale"
  resources :products, only: [:index, :show, :new, :create, :destroy] do
    collection do
      post "/checkout/:id", to: "products#checkout", as: "checkout"
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :categories, only: [:show]
  resources :users, only: [:show, :create]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new", as: "new_login"
  post "/login", to: "sessions#create", as: "create_login"
  delete "/logout", to: "sessions#destroy", as: "logout"
  get "/guest", to: "sessions#guest"
  resources :homes, only: [:index]
  resources :rooms, only: [:show, :create]
  resources :messages, only: [:create]
  resources :maps, only: [:index]
  get "/maps/search", to: "maps#search"
  resources :cards, only: [:show, :new] do
    collection do
      post "pay", to: "cards#pay"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :product
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  acts_as_mappable(default_units: :kms,
                   default_formula: :sphere,
                   distance_field_name: :distance,
                   lat_column_name: :latitude,
                   lng_column_name: :longitude)
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :content, presence: true
  validates :user_id, presence: true
  validates :room_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_taxons, dependent: :destroy
  has_many :taxons, through: :product_taxons
  belongs_to :user
  has_one :room, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  has_one :map, dependent: :destroy
  accepts_nested_attributes_for :map

  validates :name, presence: true, length: { minimum: 2 }
  validates :description, presence: true
  validates :pickup_times, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :image, presence: true
  validate :image_size

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "5MB以下のファイルを添付して下さい")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).present?
  end
end

app/models/product_taxon.rb
class ProductTaxon < ApplicationRecord
  belongs_to :product
  belongs_to :taxon
  validates :taxon_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :memberships, dependent: :destroy
  belongs_to :product

  validates :product_id, presence: true
end

app/models/taxon.rb
class Taxon < ApplicationRecord
  has_many :product_taxons, dependent: :destroy
  has_many :products, through: :product_taxons
  acts_as_nested_set
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :cards, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :memberships, dependent: :destroy

  authenticates_with_sorcery!
  mount_uploader :image, ImageUploader

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true,
                                    if: -> { new_record? || changes[:crypted_password] }
  validates_confirmation_of :password
  validate :image_size

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "5MB以下のファイルを添付して下さい")
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  protect_from_forgery expect: :pay
  require "payjp"

  def new
    card = current_user.cards.first
    redirect_to card_path(card.id) if card.present?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    customer = Payjp::Customer.create(card: params['payjpToken'])
    @card = Card.new(user_id: params[:current_user_id], customer_id: customer.id, card_id: customer.default_card)
    if @card.save
      redirect_to card_path(@card.id)
    else
      redirect_to new_card_path
    end
  end

  def show
    card = current_user.cards.first # DBにあるカードのデータを取得
    if card.present?
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id) # Payjpの顧客情報を取得
      @card_info = customer.cards.retrieve(card.card_id) # Payjpのカード情報を取得
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :require_login
  def index
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  skip_before_action :require_login
  def index
  end

  def search
    @latitude = params[:latitude]
    @longitude = params[:longitude]
    @maps = Map.includes(:product).within(3, origin: [params[:latitude], params[:longitude]])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  skip_before_action :require_login
  def show
    @room = Room.find(params[:id])
    if current_user.memberships.exists?(room: @room)
      @messages = @room.messages
      @message = Message.new
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @room = Room.new
    @room.product_id = params[:product_id]
    @room.memberships.build(user_id: params[:user_id])
    @room.memberships.build(user_id: current_user.id)
    @room.save
    redirect_to @room
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = "")
    base_title = "prototype"
    if page_title.blank?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/maps/index.html.erb
<script>
if( navigator.geolocation ){
  navigator.geolocation.getCurrentPosition( success, error, option);
  function success(position){
    var data = position.coords;
    var lat = data.latitude;
    var lng = data.longitude;
    window.location.href = `/maps/search?latitude=${lat}&longitude=${lng}`
  }

  function error(error){
    var errorMessage = {
      0: "原因不明のエラーが発生しました。",
      1: "位置情報が許可されませんでした。",
      2: "位置情報が取得できませんでした。",
      3: "タイムアウトしました。",
    } ;
    alert( errorMessage[error.code]);
  }
  var option = {
    "enableHighAccuracy": false,
    "timeout": 100 ,
    "maximumAge": 100 ,
  } ;
} else {
  alert("あなたの端末では、現在位置を取得できません。");
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GMAPS_API_KEY"] %>"></script>

app/views/maps/search.html.erb
<% provide(:title, "マップページ") %>
<div class="main-wrapper">
  <div class="container">
    <div class="row">
      <% if @maps.present? %>
        <div id="area-map"></div>
      <% else %>
        <div class="message-apologise">
          <h3>申し訳ありませんが、半径３kmに出品された商品はないようです。</h3>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script>
function initMap(){
  var products = [
    <% @maps.each do |map| %>
    ["<%= map.product.name %>", <%= map.latitude %>, <%= map.longitude %>, <%= map.product.id %>, "<%= map.address %>"],
    <% end %>
  ];

  var map = new google.maps.Map(document.getElementById("area-map"), {
    zoom: 15,
    center: new google.maps.LatLng(<%= @latitude %>, <%= @longitude %>),
    styles: [{
        stylers: [
          { hue: "#00b7ce" }, { saturation: -50 },
          { lightness: 20 }, {gamma: 0.5 }
    ]
  }],
  });
  var infowindow = new google.maps.InfoWindow;
  var marker, i;
  for(i = 0; i < products.length; i++) {
    marker = new google.maps.Marker({
      position: new google.maps.LatLng(products[i][1], products[i][2]),
      map: map,
    });
    google.maps.event.addListener(marker, "click", (function(marker, i){
    return function(){
      infowindow.setContent(
          '<div class="infowindow">' +
          '<a href="/products/' + products[i][3] + '">' +
          '商品名:「' + products[i][0] + '」' +
          '<br>' +
          '住所:「' + products[i][4] + '」' +
          '</a>' +
          '</div>'
      );
      infowindow.open(map, marker);
    }
  })(marker, i));
  }
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GMAPS_API_KEY"] %>&callback=initMap" async defer></script>

app/views/rooms/_chat_room_title.html.erb
<div class="col-lg-8 offset-lg-2 col-sm-8 offset-sm-2">
  <div class="chat-room-title">
    <!-- <div class="chat-user-name">
      <div class="chat-user-name-tag">To:</div>
      <div class="chat-user-name-content">

      </div>
    </div> -->
    <div class="chat-product-name">
      <div class="chat-product-name-tag">About:</div>
      <div class="chat-product-name-content">
        <%= @room.product.name %>
      </div>
    </div>
  </div>
  <hr>
</div>

app/views/rooms/_message_area.html.erb
<div class="col-md-8 offset-md-2">
  <div class="message-area">
    <% if messages.present? %>
      <% messages.each do |message| %>
      <div class="message-one">
        <% user = message.user %>
        <% class_suffix = current_user == user ? "right" : "left" %>
        <div class="user-icon-<%= class_suffix %>">
          <% if message.user.image.url(:small) %>
            <%= image_tag message.user.image.url(:small) %>
          <% else %>
            <%= message.user.name %>
          <% end %>
        </div>
        <div class="balloon-<%= class_suffix %>">
          <div class="balloon-content"><%= message.content %></div>
          <div class="timestamp">
            <%= time_ago_in_words(message.created_at) %>前
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<% provide(:title, "チャットページ") %>
<div class="container">
  <div class="row">
    <%= render "chat_room_title", room: @room %>
  </div>
  <div class="row">
    <%= render "message_area", messages: @messages %>
  </div>
  <div class="row">
    <div class="col-md-8 offset-md-2" >
      <%= form_with model: @message, url: messages_path, method: :post, local: true, html: { class: "message-form"} do |f| %>
        <div class="input-message">
          <%= f.text_area :content, class: "content" %>
        </div>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.submit "+", class: "btn" %>
      <% end %>
    </div>
  </div>
</div>