config/routes.rb
Rails.application.routes.draw do
  root "homes#index"
  get "/products/search", to: "products#search"
  get "/products/:id/location", to: "products#location"
  get "/products/:id/sold", to: "products#sold", as: "sold"
  post "/products/:id/sold", to: "products#resale", as: "resale"
  resources :products, only: [:index, :show, :new, :create, :destroy] do
    collection do
      post "/checkout/:id", to: "products#checkout", as: "checkout"
    end
    resource :favorites, only: [:create, :destroy]
  end
  resources :categories, only: [:show]
  resources :users, only: [:show, :create]
  get "/signup", to: "users#new"
  get "/login", to: "sessions#new", as: "new_login"
  post "/login", to: "sessions#create", as: "create_login"
  delete "/logout", to: "sessions#destroy", as: "logout"
  get "/guest", to: "sessions#guest"
  resources :homes, only: [:index]
  resources :rooms, only: [:show, :create]
  resources :messages, only: [:create]
  resources :maps, only: [:index]
  get "/maps/search", to: "maps#search"
  resources :cards, only: [:show, :new] do
    collection do
      post "pay", to: "cards#pay"
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_taxons, dependent: :destroy
  has_many :taxons, through: :product_taxons
  belongs_to :user
  has_one :room, dependent: :destroy
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader
  has_one :map, dependent: :destroy
  accepts_nested_attributes_for :map

  validates :name, presence: true, length: { minimum: 2 }
  validates :description, presence: true
  validates :pickup_times, presence: true
  validates :price, presence: true, numericality: { only_integer: true }
  validates :image, presence: true
  validate :image_size

  def image_size
    if image.size > 5.megabytes
      errors.add(:image, "5MB以下のファイルを添付して下さい")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).present?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show, :search, :location, :sold, :resale]
  RELATING_PRODUCTS_LIMIT = 4
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    redirect_to sold_path if @product.state == "sold"

    # 関連商品表示機能
    @relating_products = Product.joins(:taxons).where("product_taxons.taxon_id":
      @product.taxon_ids).where.not(id: @product.id).distinct.
      shuffle.take(RELATING_PRODUCTS_LIMIT)

    # ダイレクトメッセージ機能
    @user = @product.user
    if current_user
      current_user_memberships = Membership.where(user_id: current_user.id)
      current_user_memberships.each do |current_user_membership|
        if current_user_membership.room.product_id == @product.id
          @room_id = current_user_membership.room_id
        else
          @room = Room.new
        end
      end
    end

    # 新規商品表示機能
    @new_release_products = Product.order(created_at: "desc")
      .where.not(id: @product.id, state: "sold").distinct.limit(4)
  end

  def new
    @product = Product.new
    @product.taxons.build
    @product.build_map
  end

  def create
    @product = Product.new(products_params)
    @product.user_id = current_user.id
    if @product.save
      redirect_to product_path(@product.id)
    else
      render "new"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to root_path
  end

  def search
    @searched_products = Product.joins(:taxons).
      where("taxons.name like ?", "%#{params[:search]}%").
      or(Product.joins(:taxons).
      where("products.name like ?", "%#{params[:search]}%"))
  end

  def location
    @product = Product.find(params[:id])

    # Google Maps表示機能
    @map = @product.map
    @current_user_latitude = params[:latitude]
    @current_user_longitude = params[:longitude]
    @product_latitude = @product.map.latitude
    @product_longitude = @product.map.longitude
    @distance = Geocoder::Calculations.distance_between([@current_user_latitude, @current_user_longitude], [@product_latitude, @product_longitude])

    # 関連商品表示機能
    @relating_products = Product.joins(:taxons).where("product_taxons.taxon_id":
      @product.taxon_ids).where.not(id: @product.id, state: "sold").distinct.
      shuffle.take(RELATING_PRODUCTS_LIMIT)

    # ダイレクトメッセージ機能
    @user = @product.user
    if current_user
      current_user_memberships = Membership.where(user_id: current_user.id)
      current_user_memberships.each do |current_user_membership|
        if current_user_membership.room.product_id == @product.id
          @room_id = current_user_membership.room_id
        else
          @room = Room.new
        end
      end
    end

    # 新規商品表示機能
    @new_release_products = Product.order(created_at: "desc")
      .where.not(id: @product.id, state: "sold").distinct.limit(4)
  end

  def sold
    @product = Product.find(params[:id])
    @product.state = "sold"
    @product.save
  end

  def resale
    @product = Product.find(params[:id])
    @product.state = "sale"
    @product.save
    redirect_to @product
  end

  def checkout
    @card = current_user.cards.first
    @product = Product.find(params[:id])
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(currency: "jpy", amount: @product.price, customer: @card.customer_id)
    redirect_to sold_path(@product)
  end

  def products_params
    params.require(:product).permit(:name, :description, :pickup_times, :image, :price, :taxon_ids,
                                    map_attributes: [:id, :address])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_chat_box.html.erb
<div class="chatBox">
  <% if current_user %>
    <% if @room_id %>
      <div class="already-has-chatting">
        <%= button_to "チャットを再開する", room_path(@room_id), method: :get, class: "restart-chat-button" %>
      </div>
    <% else %>
      <div class="start-chat">
        <%= form_with url: rooms_path, method: :post, local: true do |f| %>
          <%= hidden_field_tag :product_id, product.id %>
          <%= hidden_field_tag :user_id, user.id %>
          <%= f.submit "チャットを始める", class: "start-chat-button" %>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/products/_favorites_box.html.erb
<div class="favoritesBox">
  <% if current_user && product.user.name != current_user.name  %>
    <% if product.favorited_by?(current_user) %>
      <div class="like-you">
        <%= link_to product_favorites_path(product.id), method: :delete do %>
          <div class="disattach-star"><%= icon "fas", "star" %></div>
          <div class="like-tab">「お気に入り」済み: </div>
          <div class="like-count"><%= product.favorites.count %></div>
        <% end %>
      </div>
    <% else %>
      <div class="like-you">
        <%= link_to product_favorites_path(product.id), method: :post do %>
          <div class="attach-star"><%= icon "far", "star" %></div>
          <div class="like-tab">お気に入り登録: </div>
          <div class="like-count"><%= product.favorites.count %></div>
        <% end %>
      </div>
    <% end %>
  <% else %>
      <div class="like-tab">お気に入り数: </div>
      <div class="like-count"><%= product.favorites.count %></div>
  <% end %>
</div>

app/views/products/_product_right_side.html.erb
<div class="product-right-side">
  <div class="back-to-the-index">
    <% if product.taxons.present? %>
    <%= link_to category_path(product.taxons.first.id) do %>
      <div class="icon-reply"><%= icon "fas", "reply" %></div>
      <p>カテゴリー一覧ページへ</p>
    <% end %>
  <% end %>
  </div>
  <div class="single-nameBox">
    <h2><%= product.name %></h2>
  </div>
  <div class="single-priceBox">
    <div class="single-priceBox-sub-first">価格:</div>
    <div class="single-priceBox-sub-second">¥<%= product.price %></div>
  </div>
  <div class="descriptionBox">
    <p><%= product.description %></p>
  </div>
  <div class="pickup_timesBox">
    <div class="pickup_timesBox-sub-first">希望受け取り日時:</div>
    <div class="pickup_timesBox-sub-second"><%= product.pickup_times %></div>
  </div>
  <%= render "favorites_box", product: product %>
  <% if @map %>
    <% unless @map.latitude.blank? %>
      <div class="distanceBox">
        <div class="distance-word">現在地との距離:</div>
        <div class="distance-content"><%= @distance.truncate(2) %>km</div>
      </div>
    <% end %>
  <% end %>
  <div class="row">
    <div class="chat-space">
      <%= render "chat_box", product: product, user: user %>
    </div>
    <div class="delete-buttonBox">
      <% if current_user && product.user == current_user %>
        <form action="/products/<%= product.id %>/sold" method="get">
          <button onclick="this.from.submit()" name="name" value="sold" class="delete-button">SOLDとする</button>
        </form>
      <% end %>
    </div>
  </div>
  <% if current_user && current_user.cards.present? %>
  <div class="row">
    <div class="shopBox pl-3">
      <%= form_with(url: checkout_products_path(@product.id), method: :post, local: true) do |f| %>
        <%= f.submit "購入する", class: "buy-button" %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/products/_push_product_form.html.erb
<%= form_with(model: product, url: products_path, method: :post, local: true) do |f| %>
  <%= render "shared/error_messages", object: product %>
  <div class="form-group">
    <strong><%= f.label :name, "名称" %></strong>
    <%= f.text_field :name, class: "form-control form-control-lg" %>
  </div>
  <div class="form-group">
    <strong><%= f.label :description, "説明" %></strong>
    <%= f.text_area :description, class: "form-control form-control-lg", size: "50×200", placeholder: "品質や分量、経緯など" %>
  </div>
  <div class="form-group">
    <strong><%= f.label :pickup_times, "受取り時間" %></strong>
    <%= f.text_field :pickup_times, class: "form-control form-control-lg", placeholder: "PM 19:00前後に" %>
  </div>
  <div class="form-group">
    <strong><%= f.label :price, "価格" %></strong>
    <%= f.text_field :price, class: "form-control form-control-lg", placeholder: "700円" %>
  </div>
  <div class="form-group">
    <%= f.label :image, class: "label" do %>
      <%= icon "fas", "camera border" %>
      <%= f.file_field :image, class: "form-control image_file", accept: "image/jpeg, image/peg, image/gif, image/png" %>
    <% end %>
  </div>
  <div class="form-group col-auto taxon-select">
    <%= f.select :taxon_ids, nested_set_options(Taxon) { |i| "#{"-" * i.level} #{i.name}"} %>
  </div>
  <div class="form-group">
    <%= f.fields_for :map do |fields| %>
      <strong><%= fields.label :address, "相手と合流したい住所(市町村までで可)" %></strong>
      <%= fields.text_field :address, class: "form-control form-control-lg", placeholder: "福岡県春日市昇町" %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "出品する", class: "form-control create-button" %>
  </div>
<% end %>

app/views/products/_sold_product_right_side.html.erb
<div class="product-right-side">
  <div class="back-to-the-index">
    <%= link_to products_path do %>
      <div class="icon-reply"><%= icon "fas", "reply" %></div>
      <p>一覧ページへ戻る</p>
    <% end %>
  </div>
  <div class="single-nameBox">
    <h2><%= product.name %></h2>
  </div>
  <div class="single-priceBox">
    <div class="single-priceBox-sub-first">価格:</div>
    <div class="single-priceBox-sub-second">¥<%= product.price %></div>
  </div>
  <div class="descriptionBox">
    <p><%= product.description %></p>
  </div>
  <div class="pickup_timesBox">
    <div class="pickup_timesBox-sub-first">希望受け取り日時:</div>
    <div class="pickup_timesBox-sub-second"><%= product.pickup_times %></div>
  </div>
  <div class="row">
    <div class="delete-buttonBox">
      <% if current_user && product.user == current_user %>
        <%= form_with model: product, url: resale_path(product.id), method: :post, local: true do |f| %>
          <%= f.submit "SOLDを解除", class: "delete-button" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<% provide(:title, "商品一覧ページ") %>
<div class="main-wrapper">
  <div class="container">
    <div class="row product-lists">
      <div class="products-tab">出品リスト</div>
    </div>
    <div class="row product-lists">
      <% @products.each do |product| %>
      <%= render "shared/product_segment", product: product %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/location.html.erb
<% provide(:title, "商品詳細ページ") %>
<div class="main-wrapper">
  <section class="main-content">
    <div class="container">
      <div class="row productBox">
        <div class="col-sm-12 col-lg-6">
          <div class="imageBox">
            <div class="inside-imageBox"><%= image_tag @product.image.url(:large) %></div>
          </div>
        </div>
        <div class="col-sm-12 col-lg-6">
          <%= render "product_right_side", product: @product, user: @user %>
        </div>
      </div>
    </div>
    <% unless @map.latitude.blank? %>
    <div class="container">
      <div class="single-product-locationBox">
        <div class="row relating-products-tab">出品者の希望する合流場所</div>
        <div class="row single-product-location">
          <div id="map"></div>
        </div>
      </div>
    </div>
    <% end %>
    <% if @relating_products.present? %>
    <div class="container">
      <div class="row relating-products-tab">関連商品</div>
      <div class="row relating-products">
        <% @relating_products.each do |product| %>
          <%= render "shared/product_segment", product: product %>
        <% end %>
      </div>
    </div>
    <% end %>
    <div class="container">
      <div class="row relating-products-tab">新作商品</div>
      <div class="row relating-products">
        <% @new_release_products.each do |product| %>
          <%= render "shared/product_segment", product: product %>
        <% end %>
      </div>
    </div>
  </section>
</div>

<script>
let map
let geocoder

function initMap() {
  geocoder = new google.maps.Geocoder()
  map = new google.maps.Map(document.getElementById("map"), {
    center: { lat: <%= @map.latitude %>, lng: <%= @map.longitude %> },
    zoom: 15,
    styles: [{
        stylers: [
          { hue: "#00b7ce" }, { saturation: -50 },
          { lightness: 20 }, {gamma: 0.5 }
    ]
  }],
  });
  marker = new google.maps.Marker({
    position: { lat: <%= @map.latitude %>, lng: <%= @map.longitude %> },
    map: map
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GMAPS_API_KEY"] %>&callback=initMap" async defer></script>

app/views/products/new.html.erb
<% provide(:title, "商品出品ページ") %>
<div class="main-wrapper">
  <div class="py-3">
    <div class="container formBox">
      <div class="row">
        <div class="col-sm-12 form-title">
          <strong>出品する</strong>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-8 offset-lg-2">
          <%= render "push_product_form", product: @product %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/search.html.erb
<% provide(:title, "「#{params[:search]}」の検索ページ") %>
<div class="main-wrapper">
  <div class="container">
    <div class="row product-lists">
      <div class="products-tab">
        <%= "「#{params[:search]}」の検索結果" %></div>
      </div>
    <div class="row product-lists">
      <% @searched_products.each do |product| %>
        <%= render "shared/product_segment", product: product %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% provide(:title, "商品詳細ページ") %>
<div class="main-wrapper">
  <section class="main-content">
    <div class="container">
      <div class="row productBox">
        <div class="col-sm-12 col-lg-6">
          <div class="imageBox">
            <div class="inside-imageBox"><%= image_tag @product.image.url(:large) %></div>
          </div>
        </div>
        <div class="col-sm-12 col-lg-6">
          <%= render "product_right_side", product: @product, user: @user %>
        </div>
      </div>
    </div>
    <% if @relating_products.present? %>
    <div class="container">
      <div class="row relating-products-tab">関連商品</div>
      <div class="row relating-products">
        <% @relating_products.each do |product| %>
          <%= render "shared/product_segment", product: product %>
        <% end %>
      </div>
    </div>
    <% end %>
    <div class="container">
      <div class="row new-release-products-tab">新作商品</div>
      <div class="row new-release-products">
        <% @new_release_products.each do |product| %>
          <%= render "shared/product_segment", product: product %>
        <% end %>
      </div>
    </div>
  </section>
</div>

<script>
if( navigator.geolocation ){
  navigator.geolocation.getCurrentPosition( success, error, option);
  function success(position){
    var data = position.coords;
    var lat = data.latitude;
    var lng = data.longitude;
    window.location.href = `/products/<%= @product.id %>/location?latitude=${lat}&longitude=${lng}`
  }

  function error(error){
    var errorMessage = {
      0: "原因不明のエラーが発生しました。",
      1: "位置情報が許可されませんでした。",
      2: "位置情報が取得できませんでした。",
      3: "タイムアウトしました。",
    } ;
    alert( errorMessage[error.code]);
  }
  var option = {
    "enableHighAccuracy": false,
    "timeout": 100 ,
    "maximumAge": 100 ,
  } ;
} else {
  alert("あなたの端末では、現在位置を取得できません。");
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GMAPS_API_KEY"] %>&callback=initMap" async defer></script>

app/views/products/sold.html.erb
<% provide(:title, "商品詳細ページ") %>
<div class="main-wrapper">
  <section class="main-content">
    <div class="container">
      <div class="row productBox">
        <div class="col-sm-12 col-lg-6">
          <div class="sold-imageBox">
            <%= image_tag @product.image.url(:large) %>
            <p>---SOLD OUT---</p>
          </div>
        </div>
        <div class="col-sm-12 col-lg-6">
          <%= render "sold_product_right_side", product: @product %>
        </div>
      </div>
    </div>
  </section>
</div>